import express from 'express';
import authRoutes from './routes/auth.js';
import postsRoutes from './routes/posts.js';
import newsletterRoutes from './routes/newsletter.js';
import adminRoutes from './routes/admin.js';
import interactionsRoutes from './routes/interactions.js';
import commentsRoutes from './routes/comments.js';
import categoriesRoutes from './routes/categories.js';
import imagesRoutes from './routes/images.js';
import searchRoutes from './routes/search.js';
import dashboardRoutes from './routes/dashboard.js';
import authorsRoutes from './routes/authors.js';
import pollsRoutes from './routes/polls.js';
import collaborationsRoutes from './routes/collaborations.js';
const router = express.Router();

router.use('/auth', authRoutes);
router.use('/posts', postsRoutes);
router.use('/newsletters', newsletterRoutes);
router.use('/admin', adminRoutes);
router.use('/interactions', interactionsRoutes);
router.use('/comments', commentsRoutes);
router.use('/categories', categoriesRoutes);
router.use('/images', imagesRoutes);
router.use('/search', searchRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/authors', authorsRoutes);
router.use('/polls', pollsRoutes);
router.use('/collaborations', collaborationsRoutes);
export default router;